### ISSUE TITLE
ModuleNotFoundError: No module named 'EvaluateMDP'

### ISSUE THREAD

**Issue by ferqui** [bohnstingl/Neuromorphic_Hardware_learns_to_learn#1]
When I try to run `python -m scoop ltl-SNN-ce.py` in the software model, it gives me the following error 
```
File "ltl-SNN-ce.py", line 16, in <module>
    from StateActionOptimizee import StateActionOptimizee
  File "/content/Neuromorphic_Hardware_learns_to_learn/software/StateActionOptimizee.py", line 17, in <module>
    from StateAction import StateAction
  File "/content/Neuromorphic_Hardware_learns_to_learn/software/StateAction.py", line 20, in <module>
    import EvaluateMDP
ModuleNotFoundError: No module named 'EvaluateMDP'
```
I saw that the module `EvaluateMDP` is defined in the hardware model. It is necessary to use BrainScale 2 hardware or can we simulate it with NEST? Thank you

**Comment by bohnstingl** [comment]
Thank you for your interest in our work and for pointing out this problem.  You found the correct file which can be used directly, as it does not depend on the BrainScale 2 hardware or the NEST simulator.

The problem with the imports should be fixed in the latest commit.
